In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('mental_health_social_media_dataset.csv')

In [3]:
data.head()

,person_name,age,date,gender,platform,daily_screen_time_min,social_media_time_min,negative_interactions_count,positive_interactions_count,sleep_hours,physical_activity_min,anxiety_level,stress_level,mood_level,mental_state
0,Reyansh Ghosh,35,1/1/2024,Male,Instagram,320,160,1,2,7.4,28,2,7,6,Stressed
1,Neha Patel,24,1/12/2024,Female,Instagram,453,226,1,3,6.7,15,3,8,5,Stressed
2,Ananya Naidu,26,1/6/2024,Male,Snapchat,357,196,1,2,7.2,24,3,7,6,Stressed
3,Neha Das,66,1/17/2024,Female,Snapchat,190,105,0,1,8.0,41,2,6,6,Stressed
4,Reyansh Banerjee,31,1/28/2024,Male,Snapchat,383,211,1,2,7.1,22,3,7,6,Stressed

In [4]:
data.isna().sum()

person_name                    0
age                            0
date                           0
gender                         0
platform                       0
daily_screen_time_min          0
social_media_time_min          0
negative_interactions_count    0
positive_interactions_count    0
sleep_hours                    0
physical_activity_min          0
anxiety_level                  0
stress_level                   0
mood_level                     0
mental_state                   0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   person_name                  5000 non-null   object
 1   age                          5000 non-null   int64
 2   date                         5000 non-null   object
 3   gender                       5000 non-null   object
 4   platform                     5000 non-null   object
 5   daily_screen_time_min        5000 non-null   int64
 6   social_media_time_min        5000 non-null   int64
 7   negative_interactions_count  5000 non-null   int64
 8   positive_interactions_count  5000 non-null   int64
 9   sleep_hours                  5000 non-null   float64
 10  physical_activity_min        5000 non-null   int64
 11  anxiety_level                5000 non-null   int64
 12  stress_level                 5000 non-null   int64
 13  mood_level                   5000 non-null   int64
 14  mental_state                 5000 non-null   object
dtypes: float64(1), int64(9), object(5)
memory usage: 586.1+ KB

In [6]:
data.drop('person_name',axis=1,inplace=True)

In [7]:
data.drop('date',axis=1,inplace=True)

In [8]:
data.drop('positive_interactions_count',axis=1,inplace=True)

In [9]:
data.drop('negative_interactions_count',axis=1,inplace=True)

In [10]:
data.drop('platform',axis=1,inplace=True)

In [11]:
data.drop('gender',axis=1,inplace=True)

In [12]:
#data=pd.get_dummies(data,columns=['mental_state'],dtype='int')

In [13]:
data.describe()

,age,daily_screen_time_min,social_media_time_min,sleep_hours,physical_activity_min,anxiety_level,stress_level,mood_level
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,29.947800,373.058200,175.331600,7.134660,22.693400,2.510400,7.107600,5.625800
std,12.279936,106.003916,71.209329,0.533184,10.602862,0.794996,1.062378,0.759928
min,13.000000,140.000000,35.000000,6.400000,8.000000,1.000000,5.000000,4.000000
25%,21.000000,310.000000,118.000000,6.700000,14.000000,2.000000,6.000000,5.000000
50%,27.000000,388.000000,170.000000,7.100000,21.000000,3.000000,7.000000,6.000000
75%,35.250000,461.000000,231.000000,7.450000,29.000000,3.000000,8.000000,6.000000
max,69.000000,520.000000,338.000000,8.300000,46.000000,4.000000,9.000000,7.000000

In [14]:
X=data.drop('mental_state',axis=1)
y=data['mental_state']

In [15]:
from imblearn.over_sampling import SMOTE
sm=SMOTE()
X_sm, y_sm=sm.fit_resample(X,y)

In [16]:
y_sm.value_counts()

mental_state
Stressed    4601
Healthy     4601
At_Risk     4601
Name: count, dtype: int64

In [17]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_ss=ss.fit_transform(X_sm)

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test=train_test_split(X_ss,y_sm,test_size=0.2, random_state=20)

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf=RandomForestClassifier()

In [21]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [22]:
from sklearn.model_selection import cross_validate
res=cross_validate(rf,X_train,y_train)
res

{'fit_time': array([0.73272634, 0.67768192, 0.69527888, 0.69786453, 0.64018321]),
 'score_time': array([0.04545474, 0.03110099, 0.03166676, 0.0421958 , 0.03182054]),
 'test_score': array([1., 1., 1., 1., 1.])}

In [23]:
print('validation score:', res['test_score'].mean())

validation score: 1.0

In [24]:
test_pred=rf.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_test, test_pred)

1.0

In [26]:
train_pred=rf.predict(X_train)

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(y_train, train_pred)

1.0

In [28]:
data.head()

,age,daily_screen_time_min,social_media_time_min,sleep_hours,physical_activity_min,anxiety_level,stress_level,mood_level,mental_state
0,35,320,160,7.4,28,2,7,6,Stressed
1,24,453,226,6.7,15,3,8,5,Stressed
2,26,357,196,7.2,24,3,7,6,Stressed
3,66,190,105,8.0,41,2,6,6,Stressed
4,31,383,211,7.1,22,3,7,6,Stressed

In [29]:
import pickle
with open('rf.pkl', 'wb') as f:
    pickle.dump(rf, f)

In [30]:
with open('rf_scaler.pkl', 'wb') as f:
    pickle.dump(ss, f)